### ISSUE TITLE
separate & release generic part

### ISSUE THREAD

**Issue by petri** [seantis/libres#10]
I was be very interested in using libres, until realizing it is NOT a generic library, despite claiming to be "usable by any kind of Python project".

Please could libres be restructured so that the core concepts and facilities are data storage agnostic?

**Comment by href** [comment]
The concepts of libres could possibly be implemented in a completely different way. If I had the time (and the funding), I would love to do that. However I think that would be a rewrite, not a refactoring. As it stands libres bets heavily on SQLAlchemy and any attempt to layer that away would make things very complicated.

See also http://libres.readthedocs.org/en/latest/faq.html#why-is-database-x-not-an-option-why-does-postgresql-9-1-not-work

Do feel free to fork, borrow concepts and propose incremental changes though. Maybe this can be done step by step?
