### ISSUE TITLE
postgresql version check and example path

### ISSUE THREAD

**Issue by opensensesolutions** [seantis/libres#13]
Thanks for creating this library.  Here are two small issues I found in initial testing:
1. in context/session.py get_postgres_version tries to parse the postgresql version and the string returned in Ubuntu 18.04 throws it off:

" PostgreSQL 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit"

I changed line 73 to:
version = re.findall('PostgreSQL\s+(\S+)', version)[0]
and that works, I don't know what other distros are going to throw at it.

2. if  you "Run the Example" verbatim you get:
/home/me/libres/examples/flask$ python run.py 
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    import libres
ModuleNotFoundError: No module named 'libres'

I did this to get it working:
ln -s ../../libres/ ./

but is there a better way?

**Comment by href** [comment]
Thanks for reporting these issues. I've changed the check to use a much saner approach:
https://github.com/seantis/libres/commit/0bc4a71495d26f5642173d26d9fb8c4da1dff55f

The example should work, but it does expect that you installed libres. In your case you would have to go to the root of the source tree and use `pip install -e .` (I assume you are running in a virtual environment).

Alternatively, you can also just copy the example and run `pip install libres && pip install -r requirements.txt` in a separate virtual environment.

Let me know if any of that helps.

Note also that although we do rely on this library for all of our reservation systems (think ~100 reservations a day), it is not something I'd write the same way again. There are some data models that are questionable and could be done much better. I wrote it a few years ago when I knew a lot less than I know now.

**Comment by opensensesolutions** [comment]
Thanks, that resolves the issues I ran into.

When you say "There are some data models that are questionable " would the potential problems be scalability, extensibility, stability, or ?

I was looking at using libres for an open source public computer reservation system that could deal with 100-10000 reservations a day with continual lookup, modification, and deletion.  Do you think libres might be suitable for this or should I look for a different library?

**Comment by href** [comment]
I would say the potential problem you might run into is mainly scalability. Though the mechanism for ensuring that no allocation is accidentally reserved twice is solid, it is also implemented in a way that is a bit wasteful depending on how you use it. Stability should be fine.

I don't necessarily want to discourage you, but we do not deal with 10'000 reservations a day so I don't know if it would be good enough for that. I would say that you might be a bit on your own and that we are somewhat limited in what we can do with the library at this point, so if you need extensive changes you might want to fork.

As it is we will keep the lights on with this library as we do actively use it, but we won't change it too wildly at this point and we might also consider a rewrite sometime in the future.
